package com.rl.socialnet.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF284BDC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4767F6)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFF4F5A97)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFAFBAFE)
val onSecondaryContainerLight = Color(0xFF3D4984)
val tertiaryLight = Color(0xFF9529A3)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB246BF)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B24)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B24)
val surfaceVariantLight = Color(0xFFE1E1F4)
val onSurfaceVariantLight = Color(0xFF444655)
val outlineLight = Color(0xFF747686)
val outlineVariantLight = Color(0xFFC4C5D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3039)
val inverseOnSurfaceLight = Color(0xFFF1EFFC)
val inversePrimaryLight = Color(0xFFB9C3FF)
val surfaceDimLight = Color(0xFFDAD9E5)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FF)
val surfaceContainerLight = Color(0xFFEEEDF9)
val surfaceContainerHighLight = Color(0xFFE8E7F3)
val surfaceContainerHighestLight = Color(0xFFE2E1ED)



val primaryDark = Color(0xFFB9C3FF)
val onPrimaryDark = Color(0xFF00228B)
val primaryContainerDark = Color(0xFF6F88FF)
val onPrimaryContainerDark = Color(0xFF000B42)
val secondaryDark = Color(0xFFB9C3FF)
val onSecondaryDark = Color(0xFF1F2B65)
val secondaryContainerDark = Color(0xFF37427D)
val onSecondaryContainerDark = Color(0xFFA6B1F4)
val tertiaryDark = Color(0xFFFCAAFF)
val onTertiaryDark = Color(0xFF580064)
val tertiaryContainerDark = Color(0xFFD364DE)
val onTertiaryContainerDark = Color(0xFF27002D)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12131B)
val onBackgroundDark = Color(0xFFE2E1ED)
val surfaceDark = Color(0xFF12131B)
val onSurfaceDark = Color(0xFFE2E1ED)
val surfaceVariantDark = Color(0xFF444655)
val onSurfaceVariantDark = Color(0xFFC4C5D7)
val outlineDark = Color(0xFF8E90A1)
val outlineVariantDark = Color(0xFF444655)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E1ED)
val inverseOnSurfaceDark = Color(0xFF2F3039)
val inversePrimaryDark = Color(0xFF2B4EDE)
val surfaceDimDark = Color(0xFF12131B)
val surfaceBrightDark = Color(0xFF383942)
val surfaceContainerLowestDark = Color(0xFF0C0E16)
val surfaceContainerLowDark = Color(0xFF1A1B24)
val surfaceContainerDark = Color(0xFF1E1F28)
val surfaceContainerHighDark = Color(0xFF282932)
val surfaceContainerHighestDark = Color(0xFF33343D)
